#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : ripgrep
Version  : 12.1.1
Release  : 3
URL      : file:///insilications/build/clearlinux/packages/ripgrep/ripgrep-12.1.1.tar.gz
Source0  : file:///insilications/build/clearlinux/packages/ripgrep/ripgrep-12.1.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: ripgrep-bin = %{version}-%{release}
Requires: ripgrep-data = %{version}-%{release}
BuildRequires : ca-certs
BuildRequires : ca-certs-static
BuildRequires : grep
BuildRequires : openssl
BuildRequires : openssl-dev
BuildRequires : rustc
BuildRequires : rustc-bin
BuildRequires : rustc-data
BuildRequires : rustc-dev
BuildRequires : rustc-staticdev
BuildRequires : termcolor
BuildRequires : time
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This directory contains updated benchmarks as of 2018-01-08. They were captured
via the benchsuite script at `benchsuite/benchsuite` from the root of this
repository. The command that was run:

%package bin
Summary: bin components for the ripgrep package.
Group: Binaries
Requires: ripgrep-data = %{version}-%{release}

%description bin
bin components for the ripgrep package.


%package data
Summary: data components for the ripgrep package.
Group: Data

%description data
data components for the ripgrep package.


%prep
%setup -q -n ripgrep
cd %{_builddir}/ripgrep

%build
unset http_proxy
unset https_proxy
unset no_proxy
RUSTFLAGS="-C target-cpu=native"
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
cargo update --verbose

%install
RUSTFLAGS="-C target-cpu=native"
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
RUSTFLAGS="-C target-cpu=native" cargo install --verbose --no-track --path . --root %{buildroot}/usr/ --features 'pcre2 simd-accel'
## install_append content
# shell completion for bash
install -dm 0755 %{buildroot}/usr/share/bash-completion/completions
install -m0644 ./target/release/build/ripgrep-*/out/rg.bash %{buildroot}/usr/share/bash-completion/completions/rg
rm -rf ./target/release/build/ripgrep-*/out/rg.bash
# man docs
#install -dm 0755 %{buildroot}/usr/share/man/man1
#install -m0644 ./target/release/build/ripgrep-*/out/rg.1 %{buildroot}/usr/share/man/man1/rg.1
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rg

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/rg
